### PR TITLE
Add email export, implement export for paragraph and headings

### PR DESCRIPTION
**Pull request by Artmadiar**
## Description

Allow to get email html from current editor instance and  content.

Fixes # (issue)

## Type of change

Please tick the relevant option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by martmalo** [comment]
Is this still being worked on? I also need email export and wanna join to help.

**Comment by Darginec05** [comment]
Hi @martmalo, yes this it's still in progress.
We have already implemented half of the packages for serialization and it works fine.
And of course you can join.

Do you have discord?

([Link](https://discord.com/invite/Dt8rhSTjsn) - join us if you have)

**Comment by martmalo** [comment]
> Hi @martmalo, yes this it's still in progress. We have already implemented half of the packages for serialization and it works fine. And of course you can join.
> 
> Do you have discord?
> 
> ([Link](https://discord.com/invite/Dt8rhSTjsn) - join us if you have)

What's there left to do then? Bugs and tests?

**Comment by gloaysa** [comment]
I'm thinking of use cases for this and it would be really cool to be able to add variables so we could do some search and replace before sending automated emails (things like userName and stuff like that).

I know that I can just pick some pattern on my own like `Hi ${userName}` and then search and replace, but would it make sense to create a plugin that will highlight it as a variable?

This would be really valuable specially when you have business people messing with them. It would make very obvious the part they can't touch 😄

**Comment by martmalo** [comment]
> I'm thinking of use cases for this and it would be really cool to be able to add variables so we could do some search and replace before sending automated emails (things like userName and stuff like that).
> 
> I know that I can just pick some pattern on my own like `Hi ${userName}` and then search and replace, but would it make sense to create a plugin that will highlight it as a variable?
> 
> This would be really valuable specially when you have business people messing with them. It would make very obvious the part they can't touch 😄

That is a great idea. This would go hand in hand with marketing emails where you need to have placeholders for firstName and lastName.

**Comment by Darginec05** [comment]
@gloaysa @martmalo this is actually good feature and idea, but I think it should be implemented as the next feature, because these template strings should work not only for emails, but for the entire editor.

**Comment by Artmadiar** [comment]
@gloaysa  user friendly variables could be implemented as Mark to support it in any place and plugin.
Later, on the end render we could find all marked text pieces to replace it without loosing any other marks.

**Review by Darginec05 — APPROVED** [review]

**Pull request merged**
