### PR TITLE
v4.8.0

### PR DESCRIPTION
**Pull request by Darginec05**
Fixes # (issue)

- https://github.com/Darginec05/Yoopta-Editor/issues/290
- https://github.com/Darginec05/Yoopta-Editor/issues/289
- https://github.com/Darginec05/Yoopta-Editor/issues/288
- https://github.com/Darginec05/Yoopta-Editor/issues/287
- https://github.com/Darginec05/Yoopta-Editor/issues/264
- https://github.com/Darginec05/Yoopta-Editor/issues/266
- https://github.com/Darginec05/Yoopta-Editor/issues/271
- https://github.com/Darginec05/Yoopta-Editor/issues/283
- https://github.com/Darginec05/Yoopta-Editor/issues/260
- https://github.com/Darginec05/Yoopta-Editor/issues/239
- https://github.com/Darginec05/Yoopta-Editor/issues/201
- https://github.com/Darginec05/Yoopta-Editor/issues/157
- https://github.com/Darginec05/Yoopta-Editor/issues/69
- https://github.com/Darginec05/Yoopta-Editor/issues/286
- https://github.com/Darginec05/Yoopta-Editor/issues/195
- https://github.com/Darginec05/Yoopta-Editor/issues/120
- https://github.com/Darginec05/Yoopta-Editor/issues/304

### CODE REVIEW

**Comment by cruzlutor** [comment]
Table plugin! awesome <3

**Comment by Darginec05** [comment]
@cruzlutor Do you wanna check Table plugin in action? :D 
Try demo link with `-rc` version - https://yoopta-editor-ffxdyxq73-dargos-projects.vercel.app/examples/withBaseFullSetup

**Comment by trancethehuman** [comment]
Can't wait

**Comment by Darginec05** [comment]
* Table plugin 
* Multi selection
* Divider plugin
* Markdown deseralize/serialize fixes
* Markdown deseralize/serialize fixes
* Commands API
* Events API: `onBeforeCreate`, `onCreate`, `onDestroy`
* Extensions for slate editor
* Landing is updated

**Comment by trancethehuman** [comment]
Time to upgrade and test

**Pull request merged**
